version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: yarn start
    environment:
      - PORT=3000
      - STORAGE_TYPE=s3
      - MONGO_URI=mongodb+srv://bv_moveis:BjwPMGscAtAOZjXh@noding.hfnrk.mongodb.net/bv_moveis?retryWrites=true&w=majority
      - BUCKET_NAME=bv-moveis
      - AWS_ACCESS_KEY_ID=AKIA3T4NEEWXA7HRXH43
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION=sa-east-1