version: "3.8"

services:
  bv-back:
    image: brunodevcode/bv-back:latest
    restart: always
    networks:
      - web
      - default
    expose:
      - "3000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:api.bvmoveisrusticos.com.br"
      - "traefik.basic.port=3000"
      - "traefik.basic.protocol=http"
    command: yarn start
    env_file: ./.env

networks:
  web:
    external: true